dependencies:
  - alias: expose
    name: exposecontroller
    repository: http://chartmuseum.jenkins-x.io
    version: 2.3.111
  - alias: cleanup
    name: exposecontroller
    repository: http://chartmuseum.jenkins-x.io
    version: 2.3.111
  - alias: nuxeo
    name: nuxeo
    version: 1.1.1
    repository: https://chartmuseum.platform.dev.nuxeo.com
