mongodb:
  labels:
    branch: $BRANCH_NAME
    resource: deployment
    team: platform
    usage: utests
  podLabels:
    branch: $BRANCH_NAME
    resource: pod
    team: platform
    usage: utests
tags:
  mongodb: true
